### ISSUE TITLE
Major color changes after last update 0.9.12

### ISSUE THREAD

**Issue by artilishes** [sujan-s/code-blue#18]
Hi,
I noticed some major color changes in the latest update and wondering if they were intended, since your changelog says 'Minor tweaks across the board'. To me some of those colors seem very off the initial composition. Or is it only me seeing this?
I already tried to un- & reinstall the theme. The issue persists. I'm on the latest version of VS Code.

Cheers and keep up the good work.

<img width="369" alt="Bildschirmfoto 2019-12-09 um 13 59 50" src="https://user-images.githubusercontent.com/7228414/70437574-31b65d00-1a8c-11ea-91ba-f108f2d4a8cd.png">
<img width="457" alt="Bildschirmfoto 2019-12-09 um 13 59 40" src="https://user-images.githubusercontent.com/7228414/70437575-31b65d00-1a8c-11ea-93b4-3d8af5195356.png">

**Comment by sujan-s** [comment]
Guten tag, Arthur! Flattered that your first ever issue was with Code Blue 🍻

So—yes, there are quite a few changes from `0.9.11`, and some of them drastic, relatively. I got a bunch of feedback saying that some colours were too contrast-y and harsh to look at, so I had to tone them down.

If it’s a changed colour, it’s probably intentional, sorry. But if something is broken, meaning colours no showing up, let me know, I’ll fix them up. Maybe I should have committed with “Major changes across the board”, huh.

Thanks!
